#Min Distance between next Autumn World Tree:
#Range: 0 ~ 500
autumn_world_tree_mine_distance = 50
#Frozen Retreat spawn weight:
#Range: 0 ~ 100
winter_biome_weight = 20
#max vein size for Fey Gems:
#Range: 0 ~ 20
fey_gem_max_vein_size = 5
#Average Distance between next Blacksmith:
#Range: 0 ~ 500
blacksmith_average_distance = 50
#Should the Feywild Lexicon be avialable on login: 
spawn_with_book = true
#Average Distance between next Spring World Tree:
#Range: 0 ~ 500
spring_world_tree_average_distance = 100
#Min Distance between next Summer World Tree:
#Range: 0 ~ 500
summer_world_tree_mine_distance = 50
#Spawn spring tree patches:
spring_tree_patch = true
#max height for Fey Gems:
#Range: 0 ~ 64
fey_gem_max_height = 48
#Size of the Fey Tree patches:
#Range: 0 ~ 10
tree_patches_size = 3
#Chance of Fey Tree patch spawning per biome: 
#Range: 0.0 ~ 1.0
tree_patches_chance = 0.01
#How long fey dust effect lasts:
#Range: 0 ~ 180
fey_dust_duration = 15
#Spawn summer tree patches:
summer_tree_patch = true
#Average Distance between next Winter World Tree:
#Range: 0 ~ 500
winter_world_tree_average_distance = 100
#Eternal Fall spawn weight:
#Range: 0 ~ 100
autumn_biome_weight = 20
#min height for Fey Gems:
#Range: 0 ~ 64
fey_gem_min_height = 11
#This may not work, expect fatal errors, here be dragons!
# Activate beta features:
beta = false
#Spawn autumn tree patches:
autumn_tree_patch = true
#Frozen Retreat size:
#Range: 0.0 ~ 1.0
winter_biome_size = 0.005
#Note: This requires the mod: Mythic Botany. 0: feywild biomes spawn in overworld, default alfheim, 1: feywild biomes spawn in overworld, feywild features spawn in alfheim, 2: feywild biomes not active, feywild features spawn in alfheim 
#Range: 0 ~ 2
mythic = 1
#Blossoming Wealds size:
#Range: 0.0 ~ 1.0
spring_biome_size = 0.005
#Min Distance between next Blacksmith:
#Range: 0 ~ 500
blacksmith_min_distance = 25
#Average Distance between next Summer World Tree:
#Range: 0 ~ 500
summer_world_tree_average_distance = 100
#Min Distance between next Winter World Tree:
#Range: 0 ~ 500
winter_world_tree_mine_distance = 50
#Golden Seelie Fields size:
#Range: 0.0 ~ 1.0
summer_biome_size = 0.005
#Blossoming Wealds spawn weight:
#Range: 0 ~ 100
spring_biome_weight = 20
#Average Distance between next Library:
#Range: 0 ~ 500
library_average_distance = 35
#Min Distance between next Spring World Tree:
#Range: 0 ~ 500
spring_world_tree_mine_distance = 50
#Eternal Fall size:
#Range: 0.0 ~ 1.0
autumn_biome_size = 0.005
#Average Distance between next Autumn World Tree:
#Range: 0 ~ 500
autumn_world_tree_average_distance = 100
#Golden Seelie Fields spawn weight:
#Range: 0 ~ 100
summer_biome_weight = 20
#Note: This requires the mod: Dungeons Gear. Set to True if you want Schematics Items for Dungeon Gear.
dungeons_gear = true
#weight for Fey Gems:
#Range: 0 ~ 100
fey_gem_weight = 10
#Spawn winter tree patches:
winter_tree_patch = true

#Summer Pixie spawn config.
["Summer Pixie_spawn"]
	#Min to spawn in a group.
	#Range: 0 ~ 256
	min = 1
	#Max to spawn in a group.
	#Range: 0 ~ 256
	max = 1
	#List of biome types to spawn.
	biomes = "LUSH,HOT,"
	#Chance to spawn (set to 0 to disable).
	#Range: 0 ~ 256
	spawnChance = 40

#Dwarf spawn config.
[Dwarf_spawn]
	#Min to spawn in a group.
	#Range: 0 ~ 256
	min = 1
	#Max to spawn in a group.
	#Range: 0 ~ 256
	max = 1
	#List of biome types to spawn.
	biomes = "ALL,"
	#Chance to spawn (set to 0 to disable).
	#Range: 0 ~ 256
	spawnChance = 40

#Autumn Pixie spawn config.
["Autumn Pixie_spawn"]
	#Min to spawn in a group.
	#Range: 0 ~ 256
	min = 1
	#Max to spawn in a group.
	#Range: 0 ~ 256
	max = 1
	#List of biome types to spawn.
	biomes = "SWAMP,MUSHROOM,SPOOKY,FOREST,"
	#Chance to spawn (set to 0 to disable).
	#Range: 0 ~ 256
	spawnChance = 40

#Spring Pixie spawn config.
["Spring Pixie_spawn"]
	#Min to spawn in a group.
	#Range: 0 ~ 256
	min = 1
	#Max to spawn in a group.
	#Range: 0 ~ 256
	max = 1
	#List of biome types to spawn.
	biomes = "RIVER,FOREST,PLAINS,"
	#Chance to spawn (set to 0 to disable).
	#Range: 0 ~ 256
	spawnChance = 40

#Winter Pixie spawn config.
["Winter Pixie_spawn"]
	#Min to spawn in a group.
	#Range: 0 ~ 256
	min = 1
	#Max to spawn in a group.
	#Range: 0 ~ 256
	max = 1
	#List of biome types to spawn.
	biomes = "DEAD,SNOWY,COLD,"
	#Chance to spawn (set to 0 to disable).
	#Range: 0 ~ 256
	spawnChance = 40

